const fs = require('fs');

const mcqs = [
  // Part 1
  { q: "Who developed the Python programming language?", o: ["Wick van Rossum", "Rasmus Lerdorf", "Guido van Rossum", "Dennis Ritchie"], a: 2, c: "Python Basics", d: "Easy" },
  { q: "Which of the following is the correct extension for a Python file?", o: [".python", ".pl", ".py", ".pt"], a: 2, c: "Python Basics", d: "Easy" },
  { q: "How is a code block indicated in Python?", o: ["Brackets", "Indentation", "Parentheses", "Semicolons"], a: 1, c: "Python Basics", d: "Easy" },
  { q: "Is Python case-sensitive when dealing with identifiers?", o: ["No", "Yes", "Depends on the operating system", "Only for function names"], a: 1, c: "Python Basics", d: "Easy" },
  { q: "What is the maximum possible length of an identifier in Python?", o: ["31 characters", "63 characters", "79 characters", "No fixed length"], a: 3, c: "Python Basics", d: "Easy" },
  { q: "Which keyword is used to create a single-line comment in Python?", o: ["//", "/*", "#", "<!--"], a: 2, c: "Python Basics", d: "Easy" },
  { q: "Which of the following functions can display the type of a variable?", o: ["typeof()", "type()", "check()", "datatype()"], a: 1, c: "Python Basics", d: "Easy" },
  { q: "What is the default data type returned by the input() function?", o: ["int", "float", "string", "bool"], a: 2, c: "Python Basics", d: "Easy" },
  { q: "Which of the following is NOT a core built-in data type in Python?", o: ["List", "Tuple", "Class", "Dictionary"], a: 2, c: "Python Basics", d: "Easy" },
  { q: "What does the pass statement do in Python?", o: ["Exits the loop", "Skips the current iteration", "Does nothing (acts as a placeholder)", "Returns True"], a: 2, c: "Python Basics", d: "Easy" },
  // Part 2
  { q: "What is the output of the expression print(4 + 3 % 5)?", o: ["7", "2", "1", "4"], a: 0, c: "Operators", d: "Medium" },
  { q: "Which operator is used for calculating a remainder in division?", o: ["/", "//", "%", "*"], a: 2, c: "Operators", d: "Easy" },
  { q: "What is the difference between / and // operators?", o: ["/ is for division, // is for multiplication", "/ returns float division, // returns integer floor division", "/ returns floor division, // returns float division", "Both perform the exact same operation"], a: 1, c: "Operators", d: "Medium" },
  { q: "What is the output of the expression print(2 ** 3 ** 2)?", o: ["64", "512", "81", "32"], a: 1, c: "Operators", d: "Hard" },
  { q: "What will be the output of print(0.1 + 0.2 == 0.3)?", o: ["True", "False", "Error", "Machine-dependent"], a: 1, c: "Operators", d: "Hard" },
  { q: "What is the output of the evaluation print(3 < 4 < 5)?", o: ["True", "False", "Error", "None"], a: 0, c: "Operators", d: "Medium" },
  { q: "Which operator cannot be used with string operands?", o: ["+", "*", "-", "All of the mentioned"], a: 2, c: "Operators", d: "Easy" },
  { q: "What is the output of print(\"Python\" * 2)?", o: ["PythonPython", "Python 2", "Error", "None"], a: 0, c: "Operators", d: "Easy" },
  { q: "Which method can overload the == operator behavior in a class?", o: ["__init__", "__str__", "__eq__", "__match__"], a: 2, c: "Operators", d: "Medium" },
  { q: "What is the output of bool([])?", o: ["True", "False", "Error", "None"], a: 1, c: "Operators", d: "Easy" },
  // Part 3
  { q: "Which loop structure is NOT natively supported in Python?", o: ["for", "while", "do-while", "Nested loop"], a: 2, c: "Control Flow", d: "Easy" },
  { q: "Which keyword is used to skip the rest of the current iteration and move to the next?", o: ["break", "skip", "next", "continue"], a: 3, c: "Control Flow", d: "Easy" },
  { q: "What values are generated by the expression range(5)?", o: ["1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "0, 1, 2, 3, 4, 5", "1, 2, 3, 4"], a: 1, c: "Control Flow", d: "Easy" },
  { q: "What will be the output of the following code snippet?\n\ni = 1\nwhile True:\n    if i % 3 == 0:\n        break\n    print(i, end=\" \")\n    i += 1", o: ["1 2 3", "1 2", "1", "Infinite Loop"], a: 1, c: "Control Flow", d: "Medium" },
  { q: "What happens when an else block is attached to a for loop?", o: ["It executes only if the loop encounters a break.", "It executes only when the loop completes naturally without a break.", "It executes every single time during every iteration.", "It produces a SyntaxError."], a: 1, c: "Control Flow", d: "Medium" },
  // Part 4
  { q: "Which symbol bracket is used to define a list in Python?", o: ["()", "[]", "{}", "<>"], a: 1, c: "Data Structures", d: "Easy" },
  { q: "Which of the following is true about Python tuples?", o: ["They are mutable", "They use square brackets", "They are immutable", "They cannot hold duplicate values"], a: 2, c: "Data Structures", d: "Easy" },
  { q: "What will list(\"abc\") return?", o: ["['abc']", "['a', 'b', 'c']", "('a', 'b', 'c')", "Error"], a: 1, c: "Data Structures", d: "Easy" },
  { q: "What is the output of len(set([1, 2, 2, 3]))?", o: ["4", "3", "2", "1"], a: 1, c: "Data Structures", d: "Medium" },
  { q: "How do you add an element to an existing set?", o: ["append()", "add()", "insert()", "push()"], a: 1, c: "Data Structures", d: "Easy" },
  { q: "Which exception is raised when looking for a non-existent list index?", o: ["KeyError", "ValueError", "IndexError", "AttributeError"], a: 2, c: "Data Structures", d: "Easy" },
  { q: "How do you retrieve a list of all keys from a dictionary named my_dict?", o: ["my_dict.keys()", "my_dict.get_keys()", "my_dict.all_keys", "keys(my_dict)"], a: 0, c: "Data Structures", d: "Easy" },
  { q: "What is the output of the following code?\n\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)", o: ["[1, 2, 3]", "[1, 2, 3, 4]", "Error", "[4]"], a: 1, c: "Data Structures", d: "Medium" },
  { q: "What will print(type({})) output?", o: ["<class 'set'>", "<class 'dict'>", "<class 'tuple'>", "Error"], a: 1, c: "Data Structures", d: "Medium" },
  { q: "Which of these is an invalid syntax to construct a set?", o: ["set()", "{1, 2, 3}", "{}", "set([1, 2])"], a: 2, c: "Data Structures", d: "Hard" },
  // Part 5
  { q: "What is the index position of the first element in a Python string or list?", o: ["1", "-1", "0", "Any integer"], a: 2, c: "Strings", d: "Easy" },
  { q: "What is the output of \"abcdef\"[1:4]?", o: ["abc", "bcd", "bcde", "cde"], a: 1, c: "Strings", d: "Medium" },
  { q: "How do you reverse a string s using slicing?", o: ["s[1:-1]", "s[::-1]", "s[-1:1]", "s[reverse]"], a: 1, c: "Strings", d: "Medium" },
  { q: "What does the string method strip() do?", o: ["Splits the string into a list", "Converts text to lowercase", "Removes leading and trailing whitespaces", "Counts characters"], a: 2, c: "Strings", d: "Easy" },
  { q: "What is the output of print(\"abc\".replace(\"a\", \"z\"))?", o: ["abc", "zbc", "azc", "Error"], a: 1, c: "Strings", d: "Easy" },
  // Part 6
  { q: "Which keyword is used to define an inline anonymous function?", o: ["def", "inline", "anonymous", "lambda"], a: 3, c: "Functions", d: "Medium" },
  { q: "What is the purpose of *args in a function definition?", o: ["To pass a variable number of positional arguments", "To pass a variable number of keyword arguments", "To indicate a pointer target", "To enforce integer parameters"], a: 0, c: "Functions", d: "Medium" },
  { q: "What does **kwargs collect inside a function?", o: ["Lists", "Keyword arguments as a dictionary", "Positional tuples", "Set arguments"], a: 1, c: "Functions", d: "Medium" },
  { q: "What built-in function returns a tuple pairing an index with its list value?", o: ["zip()", "mapping()", "enumerate()", "index_val()"], a: 2, c: "Functions", d: "Medium" },
  { q: "Which module provides support for regular expressions in Python?", o: ["regex", "re", "expression", "string"], a: 1, c: "Functions", d: "Easy" },
  { q: "What keyword is used to pull elements from a generator function step-by-step?", o: ["return", "yield", "send", "next"], a: 1, c: "Functions", d: "Hard" },
  { q: "Which statement is true about Python memory management?", o: ["Users must manually allocate and free memory.", "It uses automatic reference counting and a garbage collector.", "It does not support dynamically sized objects.", "Memory is cleared only when the system reboots."], a: 1, c: "Functions", d: "Medium" },
  { q: "What is the primary difference between is and ==?", o: ["There is no difference.", "is compares values, == compares identity.", "is compares object identity (memory location), == compares values.", "is works only on strings, == works on numbers."], a: 2, c: "Functions", d: "Medium" },
  { q: "Which block handles clean-up actions that must execute regardless of an exception?", o: ["except", "catch", "try", "finally"], a: 3, c: "Functions", d: "Medium" },
  { q: "What does the with statement ensure when dealing with file objects?", o: ["High-speed reading", "File encryption", "Automatic closing of resources even if exceptions occur", "File conversion to JSON"], a: 2, c: "Functions", d: "Medium" }
];

const questions = [];
mcqs.forEach((m, i) => {
  questions.push({
    id: i + 1,
    type: "mcq",
    category: m.c,
    difficulty: m.d,
    question: m.q,
    options: m.o,
    answer: m.a
  });
});

questions.push({
  id: 51,
  type: "coding",
  category: "Python",
  difficulty: "Hard",
  question: "Write a Python function named `reverse_string(s)` that takes a string `s` and returns the reversed string."
});

questions.push({
  id: 52,
  type: "coding",
  category: "SQL",
  difficulty: "Hard",
  question: "Write a SQL query to find the second highest salary from an Employee table. The table has columns: Id, Salary."
});

fs.writeFileSync('public/assessment/data/questions.json', JSON.stringify(questions, null, 2));
console.log("Generated 52 questions.");
